### ISSUE TITLE
fs undefined

### ISSUE THREAD

**Issue by jannavarro** [webpack/node-libs-browser#29]
In my js file I have: 

var fs = require('fs');

when I tried fs.readFileSync(..somefile);

Error is: fs.readFileSync is not a function

Is there any setup needed?

**Comment by zenflow** [comment]
The readme says under __Module exports `fs: null // core module without browser replacement`

Also, see the [relevant source code](https://github.com/webpack/node-libs-browser/blob/master/index.js#L12)

So, `fs`, and a handful of other node core libs that are exported in this library, are not in any way implemented for browser. 

What were you expecting this to do browser-side anyways?

**Comment by jannavarro** [comment]
@zenflow Thank you. I saw the readme; I just thought that setting it to null means that some of the node-libs-browser code would set it to a default value. I am looking at atom editor's fs-plus [code] (https://github.com/atom/fs-plus/blob/master/src/fs-plus.coffee#L312) and they are using nodejs fs inside their code which is reading some file configuration on the client-side so I thought I can use fs on client-side. If this is not applicable on the browser-side do you think they did anything special to use it?

**Comment by zenflow** [comment]
Yup.. very special. Read a bit about [electron](https://github.com/atom/electron).. formerly known as atom-shell.

It's used to make desktop apps. It allows you to use both (a) nodejs API's and (b) browser API's together. There is no browser-side separate from server-side. It's just one side, and it's both brower-side and server-side. Does that make sense?

If you're making a web-app (as opposed to a desktop app), you won't be able to use the `'fs'` module in your browser-side code. What filesystem would it access? Besides [this filesystem API](http://www.html5rocks.com/en/tutorials/file/filesystem/) which is only implemented in Chrome, browsers don't grant any filesystem privileges (read or write) to web-apps. 

If you're looking to simulate the usage of `'fs'` in your browser-side code, to, for example, include static assets/files in your build, I'm sure this is possible with webpack, but I'm not yet very knowledgeable about it. 

Anyhow, we should probably close this issue since we've diverged from the topic of issues with *this* repo.

Gitter is pretty awesome for these types of conversations, and it looks like there is a [webpack community](https://gitter.im/webpack/webpack) there.

Good luck!

**Comment by jannavarro** [comment]
@zenflow I appreciate the comprehensive explanation as I am new to web programming and the info you gave me really help.

I will be translating this to a desktop app but I am first building the core structure of my app in pure javascript so that I can use it in different web frameworks such as React and Angular depending on which would fit my goals for the app. I will be using fs the same way as atom does which is to read config files. I first thought that atom did everything mainly in javascript and just used electron to translate it in a desktop app but I now realized that it is tightly coupled with electron and chromium. I will just mock the files now.
  
Thanks also for introducing me to Gifter.

**Comment by zenflow** [comment]
@jannavarro My pleasure :)

Go team open-source!
